name: dgamelaunch-config CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Try to build the testing-container setup and see if it can
    # be started healthily
    - name: Docker container test
      run: |
        utils/build-testing-container.sh --no-tty
        docker run -d --privileged dgl-test --background
        sleep 32 # TODO: can we check this more quickly?
        docker ps --filter "health=healthy" | grep `docker ps -lq`
